FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY . .

RUN dotnet restore src/Linkuity.Cli/Linkuity.Cli.csproj
RUN dotnet publish src/Linkuity.Cli/Linkuity.Cli.csproj \
    --configuration Release \
    --output /app/linkuity-cli \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/linkuity-cli /app/linkuity-cli

ENV DOTNET_EnableDiagnostics=0

ENTRYPOINT ["dotnet", "/app/linkuity-cli/Linkuity.Cli.dll"]
