using Linkuity.Core.Models;
using Linkuity.Matching.Profiles;
using Linkuity.Matching.Strategies;
using Linkuity.Matching.Strategies.Defaults;

namespace Linkuity.Infrastructure.Lucene.Tests;

/// <summary>
/// Builds EntityRecords with realistic blocking keys (generated by the default
/// person profile's blocking strategies, exactly as MatchingEngine.EnsureBlockingKeys
/// would) and hands out isolated scratch directories for index files.
/// </summary>
internal static class LuceneTestRecords
{
    private static readonly MatchingProfile Profile = DefaultMatchingProfileProvider.CreatePersonProfile();

    private static readonly IReadOnlyList<IBlockingStrategy> Strategies =
    [
        new ExactValueBlockingStrategy(),
        new TokenNameBlockingStrategy(),
        new PrefixBlockingStrategy(),
        new NGramBlockingStrategy(),
        new PhoneticBlockingStrategy(),
        CompositeBlockingStrategy.DobLastNamePhonetic()
    ];

    public static EntityRecord Person(string sourceRecordId, IDictionary<string, string> fields, Guid? id = null)
    {
        var record = new EntityRecord
        {
            Id = id ?? Guid.NewGuid(),
            ProjectId = Guid.NewGuid(),
            SourceId = Guid.NewGuid(),
            IngestBatchId = Guid.NewGuid(),
            SourceRecordId = sourceRecordId,
            Fields = new Dictionary<string, string>(fields),
            CreatedAt = new DateTimeOffset(2026, 6, 24, 12, 0, 0, TimeSpan.Zero)
        };

        var keys = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var strategy in Strategies)
            foreach (var key in strategy.GenerateKeys(record, Profile))
                keys.Add(key);

        return new EntityRecord
        {
            Id = record.Id,
            ProjectId = record.ProjectId,
            SourceId = record.SourceId,
            IngestBatchId = record.IngestBatchId,
            SourceRecordId = record.SourceRecordId,
            Fields = record.Fields,
            BlockingKeys = keys.Order(StringComparer.Ordinal).ToList(),
            CreatedAt = record.CreatedAt
        };
    }

    public static string TempDir()
    {
        var path = Path.Combine(Path.GetTempPath(), "linkuity-lucene-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }
}
